namespace TddBankingTests
{
    using System;
    using System.Collections.Generic;

    using TddBankingApp;

    public class MockUpCurrencyListing : CurrencyListing
    {
        public MockUpCurrencyListing() : base()
        {
            this.Currencies = new List<ICurrency>
            {
                new Currency("ADP", 20, 0, "Andorran Peseta", "Andorra", false, DateTime.Parse("2003-07-01 12:00:00")),
                new Currency("AED", 784, 2, "United Arab Emirates Dirham", "United Arab Emirates", true, null),
                new Currency("AFA", 4, 0, "Afghan Afghani", "Afghanistan", false, DateTime.Parse("2003-01-01 12:00:00")),
                new Currency("AFN", 971, 2, "Afghan Afghani", "Afghanistan", true, null),
                new Currency("ALK", 4, 0, "Afghan Old Lek", "Albania", false, DateTime.Parse("1989-12-01 12:00:00")),
                new Currency("ALL", 8, 2, "Albanian Lek", "Albania", true, null),
                new Currency("AMD", 51, 2, "Armenian Dram", "Armenia", true, null),
                new Currency("ANG", 532, 2, "Netherlands Antillean Guilder", "Curaçao, Sint Maarten", true, null),
                new Currency("AOA", 973, 2, "Angolan Kwanza", "Angola", true, null),
                new Currency("AOK", null, 0, "Angolan Kwanza", "Angola", false, DateTime.Parse("1991-03-01 12:00:00")),
                new Currency("AON", 24, 0, "Angolan New Kwanza", "Angola", false, DateTime.Parse("2000-02-01 12:00:00")),
                new Currency("AOR", 982, 0, "Angolan Kwanza Reajustado", "Angola", false, DateTime.Parse("2000-02-01 12:00:00")),
                new Currency("ARA", 32, 0, "Austral", "Argentina", false, DateTime.Parse("1992-01-01 12:00:00")),
                new Currency("ARP", 32, 0, "Peso Argentino", "Argentina", false, DateTime.Parse("1985-07-01 12:00:00")),
                new Currency("ARS", 32, 2, "Peso Argentine", "Argentina", true, null),
                new Currency("ATS", null, 0, "Austrian Shilling", "Austria", false, DateTime.Parse("2002-03-01 12:00:00")),
                new Currency("ARY", null, 0, "Peso", "Argentina", false, DateTime.Parse("1989-01-01 12:00:00")),
                new Currency("AUD", 36, 2, "Australian Dollar", "Australia", true, null),
                new Currency("AWG", 533, 2, "Aruban Florin", "Aruba", true, null),
                new Currency("AYM", null, 0, "Azerbaija Manat", "Azerbaijan", false, DateTime.Parse("2005-10-01 12:00:00")),
                new Currency("AZM", null, 0, "Azerbaijanian Manat", "Azerbaijan", false, DateTime.Parse("2005-12-01 12:00:00")),
                new Currency("AZN", 944, 2, "Azerbaijani Manat", "Azerbaijan", true, null),
                new Currency("BAD", 70, 0, "Dinar", "Bosnia and Herzegovina", false, DateTime.Parse("1998-07-01 12:00:00")),
                new Currency("BAM", 977, 2, "Bosnia and Herzegovina Convertible Mark", "Bosnia and Herzegovina", true, null),
                new Currency("BBD", 52, 2, "Barbados Dollar", "Barbados", true, null),
                new Currency("BDT", 50, 2, "Bangladeshi Taka", "Bangladesh", true, null),
                new Currency("BEC", 993, 0, "Belgian Convertible Franc", "Belgium", false, DateTime.Parse("1990-03-01 12:00:00")),
                new Currency("BEF", 56, 0, "Belgian Franc", "Belgium", false, DateTime.Parse("2002-03-01 12:00:00")),
                new Currency("BEL", 992, 0, "Financial Franc", "Belgium", false, DateTime.Parse("1990-03-01 12:00:00")),
                new Currency("BGJ", null, 0, "Lev A/52", "Bulgaria", false, DateTime.Parse("1990-01-01 12:00:00")),
                new Currency("BGK", null, 0, "Lev A/62", "Bulgaria", false, DateTime.Parse("1990-01-01 12:00:00")),
                new Currency("BGL", 100, 0, "Lev", "Bulgaria", false, DateTime.Parse("2003-11-01 12:00:00")),
                new Currency("BGN", 975, 2, "Bulgarian Lev", "Bulgaria", true, null),
                new Currency("BHD", 48, 3, "Bahraini Dinar", "Bahrain", true, null),
                new Currency("BIF", 108, 0, "Burundian Franc", "Burundi", true, null),
                new Currency("BMD", 60, 2, "Bermudian Dollar", "Bermuda", true, null),
                new Currency("BND", 96, 2, "Brunei Dollar", "Brunei", true, null),
                new Currency("BOB", 68, 2, "Boliviano", "Bolivia", true, null),
                new Currency("BOP", null, 0, "Peso Boliviano Franc", "Bolivia", false, DateTime.Parse("1987-02-01 12:00:00")),
                new Currency("BOV", 984, 2, "Bolivian Mvdol (funds code)", "Bolivia", true, null),
                new Currency("BRB", null, 0, "Cruziero", "Brazil", false, DateTime.Parse("1986-03-01 12:00:00")),
                new Currency("BRC", 76, 0, "Cruzado", "Brazil", false, DateTime.Parse("1989-02-01 12:00:00")),
                new Currency("BRE", 76, 0, "Cruziero", "Brazil", false, DateTime.Parse("1993-03-01 12:00:00")),
                new Currency("BRN", 76, 0, "New Cruziero", "Brazil", false, DateTime.Parse("1990-03-01 12:00:00")),
                new Currency("BRL", 986, 2, "Brazilian Real", "Brazil", true, null),
                new Currency("BRR", 987, 0, "Cruziero Real", "Brazil", false, DateTime.Parse("1994-07-01 12:00:00")),
                new Currency("BSD", 44, 2, "Bahamian Dollar", "Bahamas", true, null),
                new Currency("BTN", 64, 2, "Bhutanese Ngultrum", "Bhutan", true, null),
                new Currency("BTU", null, 8, "Bitcoin Unlimited", null, false, null),
                new Currency("BUK", null, 0, null, "Burma", false, DateTime.Parse("1990-02-01 12:00:00")),
                new Currency("BWP", 72, 2, "Botswana Pula", "Botswana", true, null),
                new Currency("BYB", 112, 0, "Belarusian Ruble", "Belarus", false, DateTime.Parse("2001-01-01 12:00:00")),
                new Currency("BYR", 974, 0, "Belarusian Ruble", "Belarus", false, DateTime.Parse("2017-01-01 12:00:00")),
                new Currency("BZD", 84, 2, "Belize Dollar", "Belize", true, null),
                new Currency("CAD", 124, 2, "Canadian Dollar", "Canada", true, null),
                new Currency("CDF", 976, 2, "Congolese Franc", "Democratic Republic of the Congo", true, null),
                new Currency("CHE", 947, 2, "WIR Euro (complementary currency)", "Switzerland", true, null),
                new Currency("CHF", 756, 2, "Swiss Franc", "Switzerland and Liechtenstein", true, null),
                new Currency("CHW", 948, 2, "WIR Franc (complementary currency)", "Switzerland", true, null),
                new Currency("CLF", 990, 0, "Unidad de Fomento (funds code)", "Chile", true, null),
                new Currency("CLP", 152, 0, "Chilean Peso", "Chile", true, null),
                new Currency("CNH", null, 2, "Chinese Yuan (when traded offshore)", "Hong Kong", false, null),
                new Currency("CNT", null, 2, "Chinese Yuan (when traded offshore)", "Taiwan", false, null),
                new Currency("CNX", null, 0, "Peoples Bank Dollar", "China", false, DateTime.Parse("1989-12-01 12:00:00")),
                new Currency("CNY", 156, 2, "Renminbi (Chinese) Yuan", "China", true, null),
                new Currency("COP", 170, 2, "Colombian Peso", "Colombia", true, null),
                new Currency("COU", 970, 2, "Unidad de Valor Real (UVR) (funds code)", "Colombia", true, null),
                new Currency("CRC", 188, 2, "Costa Rican Colon", "Costa Rica", true, null),
                new Currency("CSJ", null, 0, "Krone A/53", "Czechoslovakia", false, DateTime.Parse("1989-01-01 12:00:00")),
                new Currency("CSK", 200, 0, "Koruna", "Czechoslovakia", false, DateTime.Parse("1939-03-01 12:00:00")),
                new Currency("CUC", 931, 2, "Cuban Convertible Peso", "Cuba", true, null),
                new Currency("CUP", 192, 2, "Cuban Peso", "Cuba", true, null),
                new Currency("CVE", 132, 0, "Cape Verde Escudo", "Cabo Verde", true, null),
                new Currency("CYP", 196, 0, "Cyprus Pound", "Cyprus", false, DateTime.Parse("2008-01-01 12:00:00")),
                new Currency("CZK", 203, 2, "Czech Koruna", "Czechia", true, null),
                new Currency("DASH", null, 8, "Dash", null, false, null),
                new Currency("DDM", 278, 0, "Mark der DDM", "German Democratic Republic", false, DateTime.Parse("1990-09-01 12:00:00")),
                new Currency("DEM", 276, 0, "Mark der DDM", "Deutsche Mark", false, DateTime.Parse("2002-03-01 12:00:00")),
                new Currency("DJF", 262, 0, "Djiboutian Franc", "Djibouti", true, null),
                new Currency("DKK", 208, 2, "Danish Krone", "Denmark, Faroe Islands, Greenland", true, null),
                new Currency("DOP", 214, 2, "Dominican Peso", "Dominican Republic", true, null),
                new Currency("DZD", 12, 2, "Algerian Dinar", "Algeria", true, null),
                new Currency("ECS", 218, 0, "Sucre", "Equador", false, DateTime.Parse("2000-09-01 12:00:00")),
                new Currency("ECV", 983, 0, "Unidad de Valor Constante", "Equador", false, DateTime.Parse("2000-09-01 12:00:00")),
                new Currency("EEK", 233, 0, "Krone", "Estonia", false, DateTime.Parse("2011-01-01 12:00:00")),
                new Currency("EGP", 818, 2, "Egyptian Pound", "Egypt", true, null),
                new Currency("ERN", 232, 2, "Eritrean Nakfa", "Eritrea", true, null),
                new Currency("ESP", 724, 0, "Spanish Peseta", "Andorra", false, DateTime.Parse("2002-03-01 12:00:00")),
                new Currency("ETB", 230, 2, "Ethiopian Birr", "Ethiopia", true, null),
                new Currency("ETH", null, 18, "Ether", null, false, null),
                new Currency("EUR", 978, 2, "Euro", "European Union", true, null),
                new Currency("FIM", 246, 0, "Ãland Islands Markka", "Ãland Islands", false, DateTime.Parse("2002-03-01 12:00:00")),
                new Currency("FJD", 242, 2, "Fiji Dollar", "Fiji", true, null),
                new Currency("FKP", 238, 2, "Falkland Islands Pound", "Falkland Islands", true, null),
                new Currency("FRF", 250, 0, "French Frank", "Andorra", false, DateTime.Parse("2002-03-01 12:00:00")),
                new Currency("GBP", 826, 2, "Pound Sterling", "United Kingdom", true, null),
                new Currency("GBX", null, 2, "Penny sterling", "United Kingdom", false, null),
                new Currency("GEK", 268, 0, "Georgian Coupon", "Georgia", false, DateTime.Parse("1995-10-01 12:00:00")),
                new Currency("GEL", 981, 2, "Georgian Lari", "Georgia", true, null),
                new Currency("GGP", null, 0, "Guernsey pound", "Guernsey", false, null),
                new Currency("GHC", 288, 0, "Ghanaian Cedi", "Ghana", false, DateTime.Parse("2008-01-01 12:00:00")),
                new Currency("GHP", 939, 0, "Ghanaian Cedi", "Ghana", false, DateTime.Parse("2007-06-01 12:00:00")),
                new Currency("GHS", 936, 2, "Ghanaian Cedi", "Ghana", true, null),
                new Currency("GIP", 292, 2, "Gibraltar Pound", "Gibraltar", true, null),
                new Currency("GMD", 270, 2, "Gambian Dalasi", "Gambia", true, null),
                new Currency("GNE", null, 0, "Guinean Syli", "Guinea", false, DateTime.Parse("1989-12-01 12:00:00")),
                new Currency("GNF", 324, 0, "Guinean Franc", "Guinea", true, null),
                new Currency("GNS", null, 0, "Guinean Syli", "Guinea", false, DateTime.Parse("1986-02-01 12:00:00")),
                new Currency("GRD", 300, 0, "Drachma", "Greece", false, DateTime.Parse("2002-03-01 12:00:00")),
                new Currency("GTQ", 320, 2, "Guatemalan Quetzal", "Guatemala", true, null),
                new Currency("GQE", 226, 0, "Ekwele", "Equatorial Guinea", false, DateTime.Parse("1986-06-01 12:00:00")),
                new Currency("GWE", null, 0, "Escudo", "Guinea-Bissau", false, DateTime.Parse("1978-01-01 12:00:00")),
                new Currency("GWP", 624, 0, "Guinea-Bissau Peso", "Guinea-Bissau", false, DateTime.Parse("1997-05-01 12:00:00")),
                new Currency("GYD", 328, 2, "Guyanese Dollar", "Guyana", true, null),
                new Currency("HKD", 344, 2, "Hong Kong Dollar", "Hong Kong", true, null),
                new Currency("HNL", 340, 2, "Honduran Lempira", "Honduras", true, null),
                new Currency("HRD", 191, 2, "Croatian Dinar", "Croatia", false, DateTime.Parse("1995-01-01 12:00:00")),
                new Currency("HRK", 191, 2, "Croatian Kuna", "Croatia", false, DateTime.Parse("2015-06-01 12:00:00")),
                new Currency("HTG", 332, 2, "Haitian Gourde", "Haiti", true, null),
                new Currency("HUF", 348, 2, "Hungarian Forint", "Hungary", true, null),
                new Currency("IDR", 360, 2, "Indonesian Rupiah", "Indonesia", true, null),
                new Currency("ILS", 376, 2, "Israeli New Shekel", "Israel and the Palestinian Authority", true, null),
                new Currency("IMP", null, 2, "Isle of Man pound (also Manx pound)", "Isle of Man", false, null),
                new Currency("INR", 356, 2, "Indian Rupee", "India and Bhutan", true, null),
                new Currency("IQD", 368, 3, "Iraqi Dinar", "Iraq", true, null),
                new Currency("IRR", 364, 0, "Iranian Rial", "Iran", true, null),
                new Currency("ISK", 352, 0, "Icelandic Króna", "Iceland", true, null),
                new Currency("ITL", 380, 0, "Italian Lira", "Italy and Vatican City State", false, DateTime.Parse("2002-03-01 12:00:00")),
                new Currency("JEP", null, 0, "Jersey pound", "Jersey", false, null),
                new Currency("JMD", 388, 2, "Jamaican Dollar", "Jamaica", true, null),
                new Currency("JOD", 400, 3, "Jordanian Dinar", "Jordan", true, null),
                new Currency("JPY", 392, 0, "Japanese Yen", "Japan", true, null),
                new Currency("KES", 404, 2, "Kenyan Shilling", "Kenya", true, null),
                new Currency("KGS", 417, 2, "Kyrgyzstani Som", "Kyrgyzstan", true, null),
                new Currency("KHR", 116, 2, "Cambodian Riel", "Cambodia", true, null),
                new Currency("KES", 404, 2, "Kenyan Shilling", "Kenya", true, null),
                new Currency("KID", null, 2, "Kiribati dollar", "Kiribati", false, null),
                new Currency("KPW", 408, 0, "North Korean Won", "North Korea", true, null),
                new Currency("KRW", 410, 0, "South Korean Won", "South Korea", true, null),
                new Currency("KWD", 414, 3, "Kuwaiti Dinar", "Kuwait", true, null),
                new Currency("KYD", 136, 2, "Cayman Islands Dollar", "Cayman Islands", true, null),
                new Currency("KZT", 398, 2, "Kazakhstani Tenge", "Kazakhstan", true, null),
                new Currency("LAK", 418, 0, "Lao Kip", "Laos", true, null),
                new Currency("LBP", 422, 0, "Lebanese Pound", "Lebanon", true, null),
                new Currency("LKR", 144, 2, "Sri Lankan Rupee", "Sri Lanka", true, null),
                new Currency("LRD", 430, 2, "Liberian Dollar", "Liberia", true, null),
                new Currency("LSL", 426, 2, "Lesotho Loti", "Lesotho", true, null),
                new Currency("LYD", 434, 3, "Libyan Dinar", "Libya", true, null),
                new Currency("MAD", 504, 2, "Moroccan Dirham", "Morocco", true, null),
                new Currency("MDL", 498, 2, "Moldovan Leu", "Moldova", true, null),
                new Currency("MGA", 969, 2, "Malagasy Ariary", "Madagascar", true, null),
                new Currency("MKD", 807, 0, "Macedonian Denar", "Macedonia", true, null),
                new Currency("MMK", 104, 0, "Myanmar Kyat", "Myanmar", true, null),
                new Currency("MNT", 496, 2, "Mongolian Tögrög", "Mongolia", true, null),
                new Currency("MOP", 446, 2, "Macanese Pataca", "Macau", true, null),
                new Currency("MRO", 478, 2, "Mauritanian Ouguiya", "Mauritania", true, null),
                new Currency("MUR", 480, 2, "Mauritian Rupee", "Mauritius", true, null),
                new Currency("MVR", 462, 2, "Maldivian Rufiyaa", "Maldives", true, null),
                new Currency("MWK", 454, 2, "Malawian Kwacha", "Malawi", true, null),
                new Currency("MXN", 484, 2, "Mexican Peso", "Mexico", true, null),
                new Currency("MXV", 979, 2, "Mexican Unidad de Inversion (UDI) (funds code)", "Mexico", true, null),
                new Currency("MYR", 458, 2, "Malaysian Ringgit", "Malaysia", true, null),
                new Currency("MZN", 943, 2, "Mozambican Metical", "Mozambique", true, null),
                new Currency("NAD", 516, 2, "Namibian dollar", "Namibia", true, null),
                new Currency("NGN", 566, 2, "Nigerian Naira", "Nigeria", true, null),
                new Currency("NIO", 558, 2, "Nicaraguan Córdoba", "Nicaragua", true, null),
                new Currency("NIS", null, 2, "Israeli New Shekel", "Israel", false, null),
                new Currency("NOK", 578, 2, "Norwegian Krone", "Norway, Svalbard and Jan Mayen, and Bouvet Island", true, null),
                new Currency("NPR", 524, 2, "Nepalese Rupee", "Nepal", true, null),
                new Currency("NTD", null, 2, "New Taiwan dollar", "Taiwan", false, null),
                new Currency("NZD", 554, 2, "New Zealand Dollar", "New Zealand, Cook Islands, Niue, Pitcairn Islands, Tokelau", true, null),
                new Currency("OMR", 512, 3, "Omani Rial", "Oman", true, null),
                new Currency("PAB", 590, 2, "Panamanian Balboa", "Panama", true, null),
                new Currency("PEN", 604, 2, "Peruvian Sol", "Peru", true, null),
                new Currency("PGK", 598, 2, "Papua New Guinean Kina", "Papua New Guinea", true, null),
                new Currency("PHP", 608, 2, "Philippine Peso", "Philippines", true, null),
                new Currency("PKR", 586, 2, "Pakistani Rupee", "Pakistan", true, null),
                new Currency("PLN", 985, 2, "Polish Złoty", "Poland", true, null),
                new Currency("PRB", null, 2, "Transnistrian ruble", "Transnistria", false, null),
                new Currency("PYG", 600, 0, "Paraguayan Guaraní", "Paraguay", true, null),
                new Currency("QAR", 634, 2, "Qatari Riyal", "Qatar", true, null),
                new Currency("RMB", null, 2, "Renminbi (Chinese) yuan", "Mainland China (from its official name RenMinBi)", false, null),
                new Currency("RON", 946, 2, "Romanian Leu", "Romania", true, null),
                new Currency("RSD", 941, 2, "Serbian Dinar", "Serbia", true, null),
                new Currency("RUB", 643, 2, "Russian Ruble", "Russia", true, null),
                new Currency("RUR", 810, 0, "Russian Ruble", "Armenia", false, DateTime.Parse("1994-08-01 12:00:00")),
                new Currency("RWF", 646, 0, "Rwandan Franc", "Rwanda", true, null),
                new Currency("SAR", 682, 2, "Saudi Riyal", "Saudi Arabia", true, null),
                new Currency("SBD", 90, 2, "Solomon Islands Dollar", "Solomon Islands", true, null),
                new Currency("SCR", 690, 2, "Seychelles Rupee", "Seychelles", true, null),
                new Currency("SDG", 938, 2, "Sudanese Pound", "Sudan", true, null),
                new Currency("SEK", 752, 2, "Swedish Krona/Kronor", "Sweden", true, null),
                new Currency("SGD", 702, 2, "Singapore Dollar", "Singapore", true, null),
                new Currency("SHP", 654, 2, "Saint Helena Pound", "Saint Helena, Ascension Island, Tristan da Cunha", true, null),
                new Currency("SLL", 694, 0, "Sierra Leonean Leone", "Sierra Leone", true, null),
                new Currency("SLS", null, 2, "Somaliland shilling", "Somaliland", false, null),
                new Currency("SOS", 706, 2, "Somali Shilling", "Somalia", true, null),
                new Currency("SRD", 968, 2, "Surinamese Dollar", "Suriname", true, null),
                new Currency("SSP", 728, 2, "South Sudanese Pound", "South Sudan", true, null),
                new Currency("STN", 678, 0, "São Tomé and Príncipe Dobra", "São Tomé and Príncipe", true, null),
                new Currency("SVC", 222, 2, "Salvadoran Colón", "El Salvador", true, null),
                new Currency("SYP", 760, 2, "Syrian Pound", "Syria", true, null),
                new Currency("SZL", 748, 2, "Swazi Lilangeni", "Eswatini", true, null),
                new Currency("THB", 764, 2, "Thai Baht", "Thailand", true, null),
                new Currency("TJS", 972, 2, "Tajikistani Somoni", "Tajikistan", true, null),
                new Currency("TMT", 934, 2, "Turkmenistan Manat", "Turkmenistan", true, null),
                new Currency("TND", 788, 3, "Tunisian Dinar", "Tunisia", true, null),
                new Currency("TOP", 776, 2, "Tongan Paʻanga", "Tonga", true, null),
                new Currency("TRY", 949, 2, "Turkish Lira", "Turkey", true, null),
                new Currency("TTD", 780, 2, "Trinidad and Tobago Dollar", "Trinidad and Tobago", true, null),
                new Currency("TVD", null, 2, "Tuvalu dollar", "Tuvalu", false, null),
                new Currency("TWD", 901, 2, "New Taiwan Dollar", "Taiwan", true, null),
                new Currency("TZS", 834, 2, "Tanzanian Shilling", "Tanzania", true, null),
                new Currency("UAH", 980, 2, "Ukrainian Hryvnia", "Ukraine", true, null),
                new Currency("UGX", 800, 2, "Ugandan Shilling", "Uganda", true, null),
                new Currency("USD", 840, 2, "United States Dollar", "United States of America, American Samoa, Barbados, Bermuda, British Indian Ocean Territory, British Virgin Islands, Caribbean Netherlands, Ecuador, El Salvador, Guam, Haiti, Marshall Islands, Federated States of Micronesia, Northern Mariana Islands, Palau, Panama, Puerto Rico, Timor-Leste, Turks and Caicos Islands, U.S. Virgin Islands, and United States Minor Outlying Islands", true, null),
                new Currency("USN", 997, 2, "United States Dollar (next day) (funds code)", "United States of America", true, null),
                new Currency("USS", 998, 2, "United States Dollar (same day) (funds code)", "United States of America", true, null),
                new Currency("UYI", 940, 0, "Uruguay Peso en Unidades Indexadas (URUIURUI) (funds code)", "Uruguay", true, null),
                new Currency("UYU", 858, 2, "Uruguayan Peso", "Uruguay", true, null),
                new Currency("UYW", 927, 4, "Unidad Previsional", "Uruguay", true, null),
                new Currency("UZS", 860, 2, "Uzbekistan Som", "Uzbekistan", true, null),
                new Currency("VES", 937, 2, "Venezuelan Bolívar Soberano", "Venezuela", true, null),
                new Currency("VND", 704, 0, "Vietnamese Dồng", "Vietnam", true, null),
                new Currency("VTC", null, 8, "VertCoin", null, false, null),
                new Currency("VUV", 548, 0, "Vanuatu Vatu", "Vanuatu", true, null),
                new Currency("WST", 882, 2, "Samoan Tala", "Samoa", true, null),
                new Currency("XAF", 950, 0, "CFA Franc BEAC", "Cameroon, Central African Republic, Republic of the Congo, Chad, Equatorial Guinea, and Gabon", true, null),
                new Currency("XAG", 961, 0, "Silver (one troy ounce)", null, true, null),
                new Currency("XAU", 959, 0, "Gold (one troy ounce)", null, true, null),
                new Currency("XBA", 955, 0, "European Composite Unit (EURCO) (bond market unit)", null, true, null),
                new Currency("XBB", 956, 0, "European Monetary Unit (E.M.U.-6) (bond market unit)", null, true, null),
                new Currency("XBC", 957, 0, "European Unit of Account 9 (E.U.A.-9) (bond market unit)", null, true, null),
                new Currency("XBD", 958, 0, "European Unit of Account 17 (E.U.A.-17) (bond market unit)", null, true, null),
                new Currency("XBT", null, 8, "Bitcoin", null, false, null),
                new Currency("XDR", 960, 0, "Special drawing rights International Monetary Fund", "International Monetary Fund", true, null),
                new Currency("XFA", null, 2, "Africahead Ipparts (AFA collision)", null, false, null),
                new Currency("XEU", 954, 0, "European Currency Unit", "European Monetary Co-operation Fund", false, DateTime.Parse("1999-01-01 12:00:00")),
                new Currency("XLM", null, 8, "Stellar Lumen", null, false, null),
                new Currency("XMR", null, 12, "Monero", null, false, null),
                new Currency("XPD", 964, 0, "Palladium (one troy ounce)", null, true, null),
                new Currency("XPT", 962, 0, "Platinum (one troy ounce)", null, true, null),
                new Currency("XRP", null, 6, "Ripple", null, false, null),
                new Currency("XSU", 994, 0, "SUCRE Unified System for Regional Compensation (SUCRE)", "Unified System for Regional Compensation (SUCRE)", true, null),
                new Currency("XTS", 963, 0, "Code reserved for testing purposes", null, true, null),
                new Currency("XUA", 965, 0, "ADB Unit of Account African Development Bank", "African Development Bank", true, null),
                new Currency("XXX", 999, 0, "No currency", null, true, null),
                new Currency("XCD", 951, 2, "East Caribbean Dollar", "Anguilla, Antigua and Barbuda, Dominica, Grenada, Montserrat, Saint Kitts and Nevis, Saint Lucia, Saint Vincent and the Grenadines", true, null),
                new Currency("XOF", 952, 0, "CFA Franc BCEAO", "Benin, Burkina Faso, Côte d'Ivoire, Guinea-Bissau, Mali, Niger, Senegal, Togo", true, null),
                new Currency("XPF", 953, 0, "CFP Franc (Franc Pacifique)", "French territories of the Pacific Ocean: French Polynesia, New Caledonia, Wallis, and Futuna", true, null),
                new Currency("YER", 886, 2, "Yemeni Rial", "Yemen", true, null),
                new Currency("ZAR", 710, 2, "South African Rand", "South Africa", true, null),
                new Currency("ZEC", null, 8, "Zcash", null, false, null),
                new Currency("ZMW", 967, 2, "Zambian Kwacha", "Zambia", true, null),
                new Currency("ZWB", null, 2, "Zimbabwean bonds", "Zimbabwe", false, null),
        };
        }
    }
}